spring.application.name=msvc-usuarios
server.port=8001

 H2: base de datos en memoria, no necesita instalacion
# Se puede ver en: http://localhost:8001/h2-console
spring.datasource.url=jdbc:h2:mem:msvc_usuarios
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate crea/elimina las tablas al arrancar/parar (solo para desarrollo)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Habilita la consola web de H2
spring.h2.console.enabled=true
debug=true

